name: Call Ant Global Library 
on:
  push:
    branches:
      - main
jobs:
  preInit:
    runs-on: ubuntu-latest
    steps:
      - name: Check for properties file
        run: |
          echo "Initialization Section"
  call-global-library:
    uses: dblucas-ops/corporate-ant-global-library/.github/workflows/antCICD.yml@main
    with:
      callerRepo: call-ant-global-library
      branchName: main
      buildCmd: ant build.xml
    secrets: inherit
