name: Call Gradle Global Library
on:
  push:
    branches:
      - main
jobs:
  preInit:
    runs-on: ubuntu-latest
    steps:
      - name: Check for properties file
        run: echo "Initialization Section"
  call-global-library:
    uses: dblucas-ops/corporate-gradle-global-library/.github/workflows/gradleCICD.yml@main
    with:
      callerRepo: call-gradle-global-library
      branchName: main
      buildCmd: gradle -PmainClass=TestMain
    secrets: inherit
